version: '3.8'

services:
  inventory_management_dev:
    container_name: inventory_management_api_dev
    image: inventory_management_dev:1.0.0
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - inventory_management_mongodb
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    restart: unless-stopped

  inventory_management_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  inventory_management_mongo_express:
    container_name: inventory_management_mongo_express
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_PASSWORD}s
      ME_CONFIG_MONGODB_URL: ${DATABASE_URI}?authSource=admin
    ports:
      - 8002:8081
    depends_on:
      - inventory_management_mongodb
    restart: unless-stopped

networks:
  default:
    driver: bridge
